GET http://localhost:8000/api/category/list HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlpTTUFqUE90Mm5ZY1hrYTY0LURVQSJ9.eyJpc3MiOiJodHRwczovL2Rldi1odHV0LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJPTUVoaER0UndCVWNzb25SbVB4MzZJU0MwOG84REE3MEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDAwLyIsImlhdCI6MTYzMDMwNTMyNCwiZXhwIjoxNjMwMzkxNzI0LCJhenAiOiJPTUVoaER0UndCVWNzb25SbVB4MzZJU0MwOG84REE3MCIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.ZkBm3mS3lMFg9z_40KMj68QV4C1DMm7E4YhOprdPepo9qvRy9HjQGWzzfKS9jRkyjze0XST0Pj-z2-Kt5kucmWvqIFnwtPH2tnJHbVGF9tR2MsODVAj_ZAA0Y5Ev79zwOF7TO502DpdVY8m24TmbINDw8D29l7l51j7aVaxDTxsarO7bJYN2bzqFE2NrZh5wk3gvLv6dhGYcGt8ze_RTI7IMqLXyvH36eQN2w6JsfyFB12zrePvw1Ptm2Frd1d8eCwfDJVg92on9_EaD4c4iG3MDvOA77DSitkrXZH5o33ISjZkG3By3WjOGW7ZeaqlzvO-lWlw9ShNg_ePdAbVBqg
###